openapi: 3.0.3
info:
  title: Vendor Management System with Performance Metrics
  version: 1.0.0
  description: Vendor Management System using Django and Django REST Framework. This
    system will handle vendor profiles, track purchase orders, and calculate vendor
    performance metrics.
paths:
  /api/purchase_orders/:
    get:
      operationId: api_purchase_orders_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PurchaseOrder'
          description: ''
    post:
      operationId: api_purchase_orders_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
  /api/purchase_orders/{po_number}/:
    get:
      operationId: api_purchase_orders_retrieve
      parameters:
      - in: path
        name: po_number
        schema:
          type: string
        description: A unique value identifying this purchase order.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
    put:
      operationId: api_purchase_orders_update
      parameters:
      - in: path
        name: po_number
        schema:
          type: string
        description: A unique value identifying this purchase order.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PurchaseOrder'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
    patch:
      operationId: api_purchase_orders_partial_update
      parameters:
      - in: path
        name: po_number
        schema:
          type: string
        description: A unique value identifying this purchase order.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseOrder'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseOrder'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPurchaseOrder'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PurchaseOrder'
          description: ''
    delete:
      operationId: api_purchase_orders_destroy
      parameters:
      - in: path
        name: po_number
        schema:
          type: string
        description: A unique value identifying this purchase order.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/purchase_orders/{id}/acknowledge/:
    post:
      operationId: api_purchase_orders_acknowledge_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/purchase_orders/{id}/issue/:
    post:
      operationId: api_purchase_orders_issue_create
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          description: No response body
  /api/vendors/:
    get:
      operationId: api_vendors_list
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vendor'
          description: ''
    post:
      operationId: api_vendors_create
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vendor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vendor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vendor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
  /api/vendors/{vendor_code}/:
    get:
      operationId: api_vendors_retrieve
      parameters:
      - in: path
        name: vendor_code
        schema:
          type: string
        description: A unique value identifying this vendor.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
    put:
      operationId: api_vendors_update
      parameters:
      - in: path
        name: vendor_code
        schema:
          type: string
        description: A unique value identifying this vendor.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vendor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vendor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vendor'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
    patch:
      operationId: api_vendors_partial_update
      parameters:
      - in: path
        name: vendor_code
        schema:
          type: string
        description: A unique value identifying this vendor.
        required: true
      tags:
      - api
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedVendor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedVendor'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedVendor'
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vendor'
          description: ''
    delete:
      operationId: api_vendors_destroy
      parameters:
      - in: path
        name: vendor_code
        schema:
          type: string
        description: A unique value identifying this vendor.
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '204':
          description: No response body
  /api/vendors/{id}/performance/:
    get:
      operationId: api_vendors_performance_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoricalPerformance'
          description: ''
components:
  schemas:
    HistoricalPerformance:
      type: object
      properties:
        vendor:
          type: string
        date:
          type: string
          readOnly: true
        average_response_time:
          type: number
          format: double
          minimum: 0.0
          nullable: true
        on_time_delivery_rate:
          type: string
          readOnly: true
        quality_rating_avg:
          type: string
          readOnly: true
        fulfillment_rate:
          type: string
          readOnly: true
      required:
      - date
      - fulfillment_rate
      - on_time_delivery_rate
      - quality_rating_avg
      - vendor
    PatchedPurchaseOrder:
      type: object
      properties:
        po_number:
          type: string
          readOnly: true
        vendor:
          type: string
        order_date:
          type: string
          readOnly: true
        delivery_date:
          type: string
          format: date-time
        items: {}
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        status:
          $ref: '#/components/schemas/StatusEnum'
        quality_rating:
          type: number
          format: double
          minimum: 0.0
          nullable: true
        issue_date:
          type: string
          format: date-time
          nullable: true
        acknowledgment_date:
          type: string
          format: date-time
          nullable: true
    PatchedVendor:
      type: object
      properties:
        vendor_code:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 25
        contact_details:
          type: string
        address:
          type: string
    PurchaseOrder:
      type: object
      properties:
        po_number:
          type: string
          readOnly: true
        vendor:
          type: string
        order_date:
          type: string
          readOnly: true
        delivery_date:
          type: string
          format: date-time
        items: {}
        quantity:
          type: integer
          maximum: 9223372036854775807
          minimum: -9223372036854775808
          format: int64
        status:
          $ref: '#/components/schemas/StatusEnum'
        quality_rating:
          type: number
          format: double
          minimum: 0.0
          nullable: true
        issue_date:
          type: string
          format: date-time
          nullable: true
        acknowledgment_date:
          type: string
          format: date-time
          nullable: true
      required:
      - delivery_date
      - items
      - order_date
      - po_number
      - quantity
      - vendor
    StatusEnum:
      enum:
      - pending
      - informed
      - listed
      - completed
      - canceled
      type: string
      description: |-
        * `pending` - Pending
        * `informed` - Informed
        * `listed` - Listed
        * `completed` - Completed
        * `canceled` - Canceled
    Vendor:
      type: object
      properties:
        vendor_code:
          type: string
          readOnly: true
        name:
          type: string
          maxLength: 25
        contact_details:
          type: string
        address:
          type: string
      required:
      - address
      - contact_details
      - name
      - vendor_code
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
