# Generated by Django 5.0.4 on 2024-05-07 06:07

import core.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(default=core.models.generate_vendor_code, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('contact_details', models.TextField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_number', models.CharField(default=core.models.generate_vendor_code, max_length=6, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField()),
                ('items', models.JSONField()),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('informed', 'informed'), ('listed', 'Listed'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('quality_rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Rating cannot be negative')])),
                ('issue_date', models.DateTimeField()),
                ('acknowledgment_date', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Rate cannot be negative')])),
                ('quality_rating_avg', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Rating cannot be negative')])),
                ('average_response_time', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Time cannot be negative')])),
                ('fulfillment_rate', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0, 'Rate cannot be negative')])),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
        ),
    ]
